# Generated by Django 5.2.3 on 2025-06-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_imagen'),
        ('productos', '0003_proveedor_remove_producto_autor_producto_proveedor_and_more'),
    ]

    operations = [
    ]
