# Generated by Django 5.2.3 on 2025-07-09 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_marca_alter_categoria_options_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Marca',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('nombre', models.CharField(max_length=100)),
        #         ('nombre_es', models.CharField(max_length=100, null=True)),
        #         ('nombre_en', models.CharField(max_length=100, null=True)),
        #         ('nombre_fr', models.CharField(max_length=100, null=True)),
        #         ('descripcion', models.TextField(blank=True, null=True)),
        #         ('descripcion_es', models.TextField(blank=True, null=True)),
        #         ('descripcion_en', models.TextField(blank=True, null=True)),
        #         ('descripcion_fr', models.TextField(blank=True, null=True)),
        #         ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
        #         ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
        #     ],
        #     options={
        #         'verbose_name': 'Marca',
        #         'verbose_name_plural': 'Marcas',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Proveedor',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('nombre', models.CharField(max_length=100)),
        #         ('nombre_es', models.CharField(max_length=100, null=True)),
        #         ('nombre_en', models.CharField(max_length=100, null=True)),
        #         ('nombre_fr', models.CharField(max_length=100, null=True)),
        #         ('descripcion', models.TextField(blank=True, null=True)),
        #         ('descripcion_es', models.TextField(blank=True, null=True)),
        #         ('descripcion_en', models.TextField(blank=True, null=True)),
        #         ('descripcion_fr', models.TextField(blank=True, null=True)),
        #         ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
        #         ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
        #     ],
        #     options={
        #         'verbose_name': 'Proveedor',
        #         'verbose_name_plural': 'Proveedores',
        #     },
        # ),
        # migrations.RemoveField(
        #     model_name='producto',
        #     name='autor',
        # ),
        # migrations.AlterModelOptions(
        #     name='categoria',
        #     options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        # ),
        # migrations.AddField(
        #     model_name='categoria',
        #     name='descripcion',
        #     field=models.TextField(blank=True, null=True),
        # ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        # migrations.AddField(
        #     model_name='producto',
        #     name='activo',
        #     field=models.BooleanField(default=True),
        # ),
        # migrations.AddField(
        #     model_name='producto',
        #     name='descripcion',
        #     field=models.TextField(blank=True, null=True),
        # ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        # migrations.AddField(
        #     model_name='producto',
        #     name='stock',
        #     field=models.PositiveIntegerField(default=1),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='categoria',
        #     name='fecha_actualizacion',
        #     field=models.DateTimeField(auto_now=True),
        # ),
        # migrations.AlterField(
        #     model_name='categoria',
        #     name='fecha_creacion',
        #     field=models.DateTimeField(auto_now_add=True),
        # ),
        # migrations.AlterField(
        #     model_name='categoria',
        #     name='nombre',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='producto',
        #     name='categorias',
        #     field=models.ManyToManyField(to='productos.categoria'),
        # ),
        # migrations.AlterField(
        #     model_name='producto',
        #     name='fecha_actualizacion',
        #     field=models.DateTimeField(auto_now=True),
        # ),
        # migrations.AlterField(
        #     model_name='producto',
        #     name='fecha_creacion',
        #     field=models.DateTimeField(auto_now_add=True),
        # ),
        # migrations.AlterField(
        #     model_name='producto',
        #     name='nombre',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='producto',
        #     name='precio',
        #     field=models.DecimalField(decimal_places=2, max_digits=10),
        # ),
        # migrations.AddField(
        #     model_name='producto',
        #     name='marca',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.marca'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='producto',
        #     name='proveedor',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.proveedor'),
        #     preserve_default=False,
        # ),
        # migrations.DeleteModel(
        #     name='Autor',
        # ),
    ]
