# Generated by Django 5.2.3 on 2025-07-09 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_marca_proveedor_remove_producto_autor_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='marca',
        #     name='descripcion_en',
        #     field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='marca',
        #     name='descripcion_es',
        #     field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='marca',
        #     name='descripcion_fr',
        #     field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='marca',
        #     name='nombre_en',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='marca',
        #     name='nombre_es',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='marca',
        #     name='nombre_fr',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='proveedor',
        #     name='descripcion_en',
        #     field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='proveedor',
        #     name='descripcion_es',
        #     field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='proveedor',
        #     name='descripcion_fr',
        #     field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='proveedor',
        #     name='nombre_en',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='proveedor',
        #     name='nombre_es',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='proveedor',
        #     name='nombre_fr',
        #     field=models.CharField(max_length=100, null=True),
        # ),
    ]
